"use client";

import React from "react";
import {
  MessageSquareQuote,
  ShieldAlert,
  Unplug,
  Box,
  Bot,
  FileLock,
  Code2,
  Sprout,
  BookX,
  Loader,
  ArrowRight,
} from "lucide-react";

const owaspItems = [
  {
    id: "01",
    title: "Prompt Injection",
    icon: MessageSquareQuote,
    color: "red",
    summary: "Attackers manipulate your AI to ignore its instructions and do their bidding.",
    realWorld: "The Klarna Incident: Hackers tricked a customer service chatbot into badmouthing the company and offering unauthorized discounts. Imagine YOUR support AI giving away free services to strangers.",
    impact: "Unauthorized access, data exposure, reputation damage",
  },
  {
    id: "02",
    title: "Sensitive Info Disclosure",
    icon: FileLock,
    color: "orange",
    summary: "Your AI accidentally reveals confidential business data, customer info, or trade secrets.",
    realWorld: "Samsung Engineers leaked proprietary source code by pasting it into ChatGPT for debugging help. The AI now \"knows\" their secrets—and so might others.",
    impact: "Client data breaches, competitive disadvantage, legal liability",
  },
  {
    id: "03",
    title: "Supply Chain Vulnerabilities",
    icon: Box,
    color: "amber",
    summary: "Third-party AI plugins, models, or integrations that come with hidden security holes.",
    realWorld: "Malicious ChatGPT plugins were found stealing user credentials and session tokens. That \"helpful\" plugin your team installed? It might be sending data elsewhere.",
    impact: "Compromised systems, unauthorized access, data theft",
  },
  {
    id: "04",
    title: "Data & Model Poisoning",
    icon: Sprout,
    color: "yellow",
    summary: "Bad actors corrupt your AI's training data, making it produce wrong or harmful outputs.",
    realWorld: "Microsoft's Tay chatbot was poisoned by trolls within 24 hours, turning it into a PR nightmare. Your custom-trained sales AI could be the next target.",
    impact: "Corrupted business intelligence, wrong decisions, brand damage",
  },
  {
    id: "05",
    title: "Insecure Output Handling",
    icon: Code2,
    color: "lime",
    summary: "Trusting AI-generated content without validation—leading to code injection or XSS attacks.",
    realWorld: "AI-generated code deployed without review contained SQL injection vulnerabilities. A consultant's AI assistant accidentally created a backdoor in their client's system.",
    impact: "System compromises, client site hacks, professional liability",
  },
  {
    id: "06",
    title: "Excessive Agency",
    icon: Bot,
    color: "emerald",
    summary: "AI systems with too much power—making purchases, sending emails, or accessing systems autonomously.",
    realWorld: "An AI assistant with email access started replying to clients with incorrect information and making calendar changes without approval. Autonomy became chaos.",
    impact: "Unauthorized transactions, client miscommunication, legal issues",
  },
  {
    id: "07",
    title: "System Prompt Leakage",
    icon: Unplug,
    color: "teal",
    summary: "Hackers extract your AI's hidden instructions, exposing your business logic and security rules.",
    realWorld: "Bing Chat's system prompt was extracted by users, revealing Microsoft's internal guidelines and content restrictions. Your AI's \"secret sauce\" could be next.",
    impact: "Competitive intelligence loss, security bypass, IP exposure",
  },
  {
    id: "08",
    title: "Vector & Embedding Weaknesses",
    icon: ShieldAlert,
    color: "cyan",
    summary: "Flaws in how AI stores and retrieves information, allowing unauthorized data access.",
    realWorld: "RAG systems (Retrieval-Augmented Generation) can be tricked into surfacing documents the user shouldn't see. Your AI assistant might accidentally share HR files with interns.",
    impact: "Data leaks, compliance violations, privacy breaches",
  },
  {
    id: "09",
    title: "Misinformation",
    icon: BookX,
    color: "blue",
    summary: "AI confidently generates false information—hallucinations that look like facts.",
    realWorld: "Lawyers cited fake court cases generated by ChatGPT and faced sanctions. Imagine your AI advisor recommending non-existent regulations to your clients.",
    impact: "Professional liability, client lawsuits, credibility destruction",
  },
  {
    id: "10",
    title: "Unbounded Consumption",
    icon: Loader,
    color: "purple",
    summary: "Attackers overload your AI systems, crashing them or running up massive bills.",
    realWorld: "Denial of Service attacks against AI APIs during Black Friday crashed customer support systems. Your busiest sales day becomes your worst nightmare.",
    impact: "Service outages, unexpected costs, lost revenue",
  },
];

const colorClasses = {
  red: { bg: "bg-red-500/10", text: "text-red-400", border: "border-red-500/20" },
  orange: { bg: "bg-orange-500/10", text: "text-orange-400", border: "border-orange-500/20" },
  amber: { bg: "bg-amber-500/10", text: "text-amber-400", border: "border-amber-500/20" },
  yellow: { bg: "bg-yellow-500/10", text: "text-yellow-400", border: "border-yellow-500/20" },
  lime: { bg: "bg-lime-500/10", text: "text-lime-400", border: "border-lime-500/20" },
  emerald: { bg: "bg-emerald-500/10", text: "text-emerald-400", border: "border-emerald-500/20" },
  teal: { bg: "bg-teal-500/10", text: "text-teal-400", border: "border-teal-500/20" },
  cyan: { bg: "bg-cyan-500/10", text: "text-cyan-400", border: "border-cyan-500/20" },
  blue: { bg: "bg-blue-500/10", text: "text-blue-400", border: "border-blue-500/20" },
  purple: { bg: "bg-purple-500/10", text: "text-purple-400", border: "border-purple-500/20" },
};

function ThreatCard({ item }: { item: typeof owaspItems[0] }) {
  const colors = colorClasses[item.color as keyof typeof colorClasses];
  const Icon = item.icon;

  return (
    <div className="group relative" style={{ perspective: "1000px" }}>
      {/* Ambient glow on hover */}
      <div className="absolute -inset-1 rounded-2xl bg-gradient-to-br from-amber-500/20 via-amber-600/10 to-transparent opacity-0 blur-xl transition-all duration-500 group-hover:opacity-100" />
      
      {/* Card with 3D effect */}
      <div
        className={`relative h-full rounded-2xl border ${colors.border} bg-card p-6 transition-all duration-300 group-hover:border-amber-500/40`}
        style={{
          transform: "translateZ(0)",
          transition: "transform 0.3s ease, box-shadow 0.3s ease",
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.transform = "translateY(-8px) rotateX(2deg) scale(1.02)";
          e.currentTarget.style.boxShadow = "0 25px 50px -12px rgba(217, 119, 6, 0.25), 0 12px 24px -8px rgba(217, 119, 6, 0.15)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.transform = "translateZ(0)";
          e.currentTarget.style.boxShadow = "none";
        }}
      >
        {/* Header */}
        <div className="mb-4 flex items-start gap-4">
          <div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-xl ${colors.bg} ${colors.text} transition-transform duration-300 group-hover:scale-110`}>
            <Icon className="h-6 w-6" />
          </div>
          <div>
            <span className={`text-xs font-bold ${colors.text}`}>LLM{item.id}</span>
            <h3 className="text-lg font-bold text-foreground">{item.title}</h3>
          </div>
        </div>

        {/* Summary */}
        <p className="mb-4 text-sm leading-relaxed text-muted-foreground">
          {item.summary}
        </p>

        {/* Real World Example */}
        <div className="mb-4 rounded-lg border border-border bg-muted/50 p-4 transition-colors duration-300 group-hover:border-amber-500/20 group-hover:bg-muted/80">
          <p className="text-xs font-semibold uppercase tracking-wider text-amber-400">
            Real-World Example
          </p>
          <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
            {item.realWorld}
          </p>
        </div>

        {/* Impact */}
        <div className="flex items-center gap-2 text-xs text-muted-foreground">
          <span className="font-semibold text-red-400">Impact:</span>
          <span>{item.impact}</span>
        </div>
      </div>
    </div>
  );
}

export function OwaspTeaser() {
  return (
    <section className="relative w-full overflow-hidden border-b border-border bg-background py-24">
      {/* Background effects */}
      <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-red-900/10 via-transparent to-transparent" />

      <div className="container relative z-10 mx-auto max-w-7xl px-4">
        {/* Section Header */}
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-red-500/20 bg-red-500/5 px-4 py-1.5">
            <span className="h-1.5 w-1.5 rounded-full bg-red-400" />
            <span className="text-sm font-medium text-red-400">
              OWASP Top 10 for LLMs
            </span>
          </div>
          <h2 className="mb-6 text-4xl font-bold tracking-tight text-foreground md:text-5xl">
            The New Frontier of{" "}
            <span className="bg-gradient-to-r from-red-400 via-orange-400 to-amber-400 bg-clip-text text-transparent">
              AI Threats
            </span>
          </h2>
          <p className="text-lg leading-relaxed text-muted-foreground">
            As SMBs rush to adopt AI, attackers are developing new ways to exploit these systems.
            Here&apos;s what every business professional needs to understand—explained in plain English with real examples.
          </p>
        </div>

        {/* Two-Column Grid */}
        <div className="grid gap-6 md:grid-cols-2">
          {owaspItems.map((item) => (
            <ThreatCard key={item.id} item={item} />
          ))}
        </div>

        {/* Bottom CTA */}
        <div className="mt-16 text-center">
          <div
            className="mx-auto inline-block rounded-2xl border border-amber-500/20 bg-card p-8"
          >
            <p className="mb-4 text-lg text-muted-foreground">
              <span className="font-bold text-foreground">Feeling overwhelmed?</span>{" "}
              That&apos;s exactly why SMBShield exists.
            </p>
            <p className="mb-6 text-muted-foreground">
              We translate these threats into actionable protection—so you can focus on your business.
            </p>
            <a
              href="#pricing"
              className="group inline-flex items-center gap-2 rounded-full border border-amber-500/30 bg-gradient-to-r from-amber-500/10 to-amber-600/10 px-6 py-3 font-semibold text-amber-400 transition-all duration-300 hover:border-amber-500/50 hover:from-amber-500/20 hover:to-amber-600/20 hover:text-amber-300"
            >
              Get Protected Now
              <ArrowRight className="h-4 w-4 transition-transform duration-300 group-hover:translate-x-1" />
            </a>
          </div>
        </div>
      </div>
    </section>
  );
}
